/**
 * Behavior signals per flattening policy. Keys are the ontology's policy names
 * (allowConcurrent / keepLatest / queueWhileBusy / ignoreWhileBusy), so this map
 * stays aligned with the graph. These phrases are what the advisor matches a
 * user's behavior description against — the one piece of knowledge that is the
 * advisor's own, layered on top of the ontology's facts.
 */
export const POLICY_SIGNALS: Record<string, string[]> = {
  allowConcurrent: [
    "parallel",
    "in parallel",
    "concurrent",
    "concurrently",
    "all at once",
    "at the same time",
    "simultaneously",
    "overlap",
    "overlapping",
    "fan out",
    "fan-out",
    "as many as possible",
    "unbounded",
    "every request runs",
    "flatten all",
    "independent requests",
  ],
  keepLatest: [
    "latest",
    "newest",
    "most recent",
    "only the last",
    "cancel",
    "cancels",
    "cancelling",
    "canceling",
    "abort",
    "replace",
    "supersede",
    "discard previous",
    "previous",
    "stale",
    "type-ahead",
    "typeahead",
    "autocomplete",
    "search-as-you-type",
    "live search",
    "cancel-and-replace",
  ],
  queueWhileBusy: [
    "queue",
    "queued",
    "in order",
    "preserve order",
    "keep order",
    "ordered",
    "sequential",
    "sequentially",
    "one at a time",
    "one after another",
    "back to back",
    "serialize",
    "serialise",
    "wait for each",
    "finish before",
    "no overlap",
    "strictly ordered",
  ],
  ignoreWhileBusy: [
    "ignore",
    "ignores",
    "drop",
    "drops",
    "skip",
    "skips",
    "while busy",
    "in flight",
    "in-flight",
    "still running",
    "already running",
    "until done",
    "prevent double",
    "double submit",
    "double-submit",
    "double click",
    "double-click",
    "dedupe",
    "deduplicate",
    "first wins",
    "rapid taps",
    "rapid clicks",
  ],
};
